import { fileURLToPath } from "node:url";
import path from "node:path";
import { drizzle, type MySql2Database } from "drizzle-orm/mysql2";
import { migrate } from "drizzle-orm/mysql2/migrator";
import mysql, { type Pool, type PoolOptions } from "mysql2/promise";

export type Db = MySql2Database;

/** A connection pool plus its typed query builder. */
export interface DbHandle {
  pool: Pool;
  db: Db;
}

export interface MysqlEndpoint {
  host: string;
  port: number;
  user: string;
  password: string;
  database?: string;
}

export const parseMysqlUrl = (url: string): MysqlEndpoint => {
  const u = new URL(url);
  if (u.protocol !== "mysql:") throw new Error("DATABASE_URL must start with mysql://");
  const database = decodeURIComponent(u.pathname.replace(/^\//, ""));
  return {
    host: u.hostname,
    port: Number(u.port || 3306),
    user: decodeURIComponent(u.username),
    password: decodeURIComponent(u.password),
    database: database || undefined,
  };
};

const BASE_OPTIONS: PoolOptions = {
  waitForConnections: true,
  charset: "utf8mb4",
  // All timestamps are stored and read as UTC.
  timezone: "Z",
  supportBigNumbers: true,
  enableKeepAlive: true,
};

export const createHandle = (options: PoolOptions): DbHandle => {
  const pool = mysql.createPool({ ...BASE_OPTIONS, ...options });
  return { pool, db: drizzle(pool) };
};

/**
 * The MySQL error code (e.g. "ER_DUP_ENTRY"), looking through the wrapper the
 * ORM puts around driver errors.
 */
export const mysqlErrorCode = (err: unknown): string | undefined => {
  let current = err as { code?: unknown; cause?: unknown } | undefined;
  for (let depth = 0; current && depth < 5; depth++) {
    if (typeof current.code === "string") return current.code;
    current = current.cause as typeof current;
  }
  return undefined;
};

/** packages/core, wherever the package is installed. */
const CORE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

const migrationsFolder = (which: "platform" | "tenant"): string =>
  path.join(process.env.DBRB_MIGRATIONS_DIR ?? path.join(CORE_ROOT, "drizzle"), which);

export const migratePlatform = (db: Db): Promise<void> =>
  migrate(db, { migrationsFolder: migrationsFolder("platform") });

export const migrateTenant = (db: Db): Promise<void> =>
  migrate(db, { migrationsFolder: migrationsFolder("tenant") });

/**
 * Quotes a database identifier for use in DDL. Names are generated by DBRB
 * (never typed by users) and restricted to [a-z0-9_], so this is defence in depth.
 */
export const quoteIdentifier = (name: string): string => {
  if (!/^[A-Za-z0-9_]{1,64}$/.test(name)) throw new Error(`Unsafe database identifier: ${name}`);
  return `\`${name}\``;
};

/**
 * Quotes a database name for a GRANT statement. In GRANT, `_` and `%` in a
 * database name are wildcards, so they must be escaped or a grant on `a_b`
 * would also match a database named `axb`.
 */
export const quoteGrantDatabase = (name: string): string => {
  if (!/^[A-Za-z0-9_]{1,64}$/.test(name)) throw new Error(`Unsafe database identifier: ${name}`);
  return `\`${name.replace(/_/g, "\\_")}\``;
};
